<#
.SYNOPSIS
    Performs weekly DLP activity monitoring check using previously generated executive summary reports.

.DESCRIPTION
    This script provides a quick monitoring dashboard for on-premises DLP activity by analyzing
    the most recent executive summary and detailed reports generated from Activity Explorer exports.
    It displays sensitive data detection statistics, repository breakdowns, and file counts to
    help compliance teams quickly assess DLP status without re-processing raw Activity Explorer data.
    
    The script automatically locates the latest reports in C:\Reports, loads the summary data,
    and presents a formatted dashboard showing:
    
    - Total unique files with sensitive data
    - Detection counts by sensitive data type (Credit Card Numbers, SSNs, etc.)
    - Repository breakdown showing which shares contain sensitive information
    - Sample file paths for quick identification
    - Report timestamps and data freshness indicators
    
    Ideal for weekly compliance reviews, stakeholder updates, and ongoing DLP monitoring cadence.
    For fresh data, re-export Activity Explorer data and re-run Generate-DLPExecutiveSummary.ps1.

.PARAMETER None
    This script requires no parameters. It automatically searches C:\Reports for the most recent
    executive summary and detailed report files.

.EXAMPLE
    .\Invoke-WeeklyDLPMonitoring.ps1
    
    Displays weekly DLP monitoring dashboard using the most recent reports in C:\Reports directory.

.NOTES
    Author: Marcus Jacobson
    Version: 1.0.0
    Created: 2025-01-10
    Last Modified: 2025-01-10
    
    Copyright (c) 2025 Marcus Jacobson. All rights reserved.
    Licensed under the MIT License.
    
    Requirements:
    - Executive summary and detailed reports must exist in C:\Reports directory
    - Reports generated by Generate-DLPExecutiveSummary.ps1 script
    - PowerShell 5.1+ or PowerShell 7+
    - Read permissions to C:\Reports directory
    
    Script development orchestrated using GitHub Copilot.

.INPUTS
    CSV files from C:\Reports directory (auto-generated by Generate-DLPExecutiveSummary.ps1):
    - OnPrem-DLP-Executive-Summary-YYYY-MM-DD.csv
    - OnPrem-DLP-Detailed-Report-YYYY-MM-DD.csv

.OUTPUTS
    Console dashboard displaying:
    - DLP activity summary by sensitive data type
    - Repository breakdown with file counts
    - Total unique files and detection events
    - Report freshness indicators and next steps
#>
#
# =============================================================================
# Weekly DLP activity monitoring check - analyzes the most recent executive
# summary and detailed reports for compliance dashboard.
# =============================================================================

Write-Host "`n========== WEEKLY DLP ACTIVITY MONITORING CHECK ==========" -ForegroundColor Cyan
Write-Host "Checking for on-premises DLP activity reports...`n" -ForegroundColor Yellow

# ============================================================
# FIND LATEST REPORTS: Look for executive summary and detailed reports
# ============================================================

$executiveSummary = Get-ChildItem "C:\Reports" -Filter "OnPrem-DLP-Executive-Summary-*.csv" -ErrorAction SilentlyContinue | 
                    Sort-Object LastWriteTime -Descending | 
                    Select-Object -First 1

$detailedReport = Get-ChildItem "C:\Reports" -Filter "OnPrem-DLP-Detailed-Report-*.csv" -ErrorAction SilentlyContinue | 
                  Sort-Object LastWriteTime -Descending | 
                  Select-Object -First 1

if ($executiveSummary) {
    Write-Host "✅ Found Executive Summary: $($executiveSummary.Name)" -ForegroundColor Green
    Write-Host "   Generated: $($executiveSummary.LastWriteTime)`n" -ForegroundColor Gray
    
    # Load executive summary data
    $summaryData = Import-Csv $executiveSummary.FullName
    
    # Display executive summary
    Write-Host "========== ON-PREMISES DLP ACTIVITY SUMMARY ==========" -ForegroundColor Cyan
    Write-Host "Report Date: $($executiveSummary.LastWriteTime.ToString('yyyy-MM-dd'))" -ForegroundColor Yellow
    Write-Host "Scope: On-Premises File Repositories (Endpoint Devices)`n" -ForegroundColor Yellow
    
    if ($summaryData.Count -eq 0) {
        Write-Host "⚠️  WARNING: No sensitive data detected in latest scan" -ForegroundColor Yellow
        Write-Host "  - Verify scanner has completed a DLP scan" -ForegroundColor Yellow
        Write-Host "  - Check Activity Explorer for recent file discovered events" -ForegroundColor Yellow
        Write-Host "  - Re-run the executive summary script with latest Activity Explorer export" -ForegroundColor Yellow
    } else {
        # Display summary by sensitive data type
        $summaryData | ForEach-Object {
            Write-Host "  $($_.'Sensitive Data Type'):" -ForegroundColor Cyan
            Write-Host "    Unique Files: $($_.'Unique Files Detected')" -ForegroundColor White
            Write-Host "    Total Events: $($_.'Total Detection Events')" -ForegroundColor White
            if ($_.'Sample Files') {
                Write-Host "    Sample Files: $($_.'Sample Files')" -ForegroundColor Gray
            }
            Write-Host ""
        }
        
        # Calculate total unique files across all data types
        $totalUniqueFiles = ($summaryData | Measure-Object -Property 'Unique Files Detected' -Sum).Sum
        $totalEvents = ($summaryData | Measure-Object -Property 'Total Detection Events' -Sum).Sum
        
        Write-Host "Total Unique Files with Sensitive Data: $totalUniqueFiles" -ForegroundColor Green
        Write-Host "Total Detection Events: $totalEvents`n" -ForegroundColor Green
    }
    
    # If detailed report exists, show repository breakdown
    if ($detailedReport) {
        Write-Host "========== REPOSITORY BREAKDOWN ==========" -ForegroundColor Cyan
        $detailedData = Import-Csv $detailedReport.FullName
        
        # Group by repository
        $repoGroups = $detailedData | Group-Object Repository | Sort-Object Count -Descending
        
        foreach ($repo in $repoGroups) {
            Write-Host "  $($repo.Name): $($repo.Count) files with sensitive data" -ForegroundColor White
            
            # Show sensitive data types in this repository
            $dataTypes = $repo.Group | Group-Object 'Sensitive Data Type'
            foreach ($type in $dataTypes) {
                Write-Host "    - $($type.Name): $($type.Count) files" -ForegroundColor Gray
            }
        }
        Write-Host ""
    }
    
    Write-Host "✅ On-premises DLP monitoring active and capturing events" -ForegroundColor Green
    Write-Host "`n💡 Next Steps:" -ForegroundColor Cyan
    Write-Host "  - Review detailed report for specific file locations" -ForegroundColor White
    Write-Host "  - Export fresh Activity Explorer data for most current status" -ForegroundColor White
    Write-Host "  - Re-run executive summary script to update reports`n" -ForegroundColor White
    
} else {
    Write-Host "⚠️  No DLP reports found in C:\Reports" -ForegroundColor Yellow
    Write-Host "`nTo generate reports:" -ForegroundColor Yellow
    Write-Host "  1. Export Activity Explorer data to CSV" -ForegroundColor White
    Write-Host "  2. Run the PowerShell Executive Summary script (Step 3 - Option 2)" -ForegroundColor White
    Write-Host "  3. Reports will be saved to C:\Reports for monitoring`n" -ForegroundColor White
}
