trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: pipeline-variables.yml

resources:
  repositories:
    - repository: <YOUR-REPOSITORY-NAME>
      type: git
      name: '<YOUR-PROJECT-NAME>/<YOUR-REPOSITORY-NAME>'

jobs:
- job: 'DeployGroup'
  displayName: 'Deploy Groups'
  steps:
  - checkout: self
    persistCredentials: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(serviceConnection)'
      addSpnToEnvironment: true
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: '$(scriptPath)'
      scriptArguments:
        -GroupsJson '$(groups)'
      