trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: pipeline-variables.yml

resources:
  repositories:
    - repository: <YOUR-REPOSITORY-NAME>
      type: git
      name: '<YOUR-PROJECT-NAME>/<YOUR-REPOSITORY-NAME>'

jobs:
- job: 'CreateNamedLocationsList'
  displayName: 'Create a new named locations list of type: IP Ranges'
  steps:
  - checkout: self
    persistCredentials: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(serviceConnection)'
      addSpnToEnvironment: true
      scriptType: pscore
      scriptPath: '$(scriptPath)'
      scriptLocation: scriptPath
      scriptArguments: 
        -IPRanges '$(ipRanges)'
        -DisplayName '$(displayName)'
        -IsTrusted '$(isTrusted)'