trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: pipeline-variables.yml

# OPTIONAL: If you need to reference additional repositories, update the values below.
# Otherwise, you can remove this entire resources section.
resources:
  repositories:
    - repository: <YOUR-REPOSITORY-ALIAS>
      type: git
      name: '<YOUR-PROJECT-NAME>/<YOUR-REPOSITORY-NAME>'

jobs:
- job: 'UpdateCompanyBranding'
  displayName: 'Update Company Branding'
  steps:
  - checkout: self
    persistCredentials: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(serviceConnection)'
      addSpnToEnvironment: true
      scriptType: pscore
      scriptPath: '$(scriptPath)'
      scriptLocation: scriptPath
      scriptArguments: 
        -BackgroundColor '$(backgroundColor)'
        -HeaderBackgroundColor '$(headerBackgroundColor)'
        -CustomPrivacyAndCookiesText '$(customPrivacyAndCookiesText)'
        -CustomTermsOfUseText '$(customTermsOfUseText)'
        -UsernameHintText '$(usernameHintText)'
        -SignInPageText '$(signInPageText)'
        -CustomCannotAccessYourAccountText '$(customCannotAccessYourAccountText)'
        -CustomForgotMyPasswordText '$(customForgotMyPasswordText)'
        -CustomResetItNowText '$(customResetItNowText)'