<#
.SYNOPSIS
    Displays the most recent site creation validation report in a formatted view.

.DESCRIPTION
    This script locates and displays the most recent site-creation-validation-report-*.json
    file from the reports folder. It provides a formatted summary of the validation results
    including site accessibility, document library presence, ownership configuration,
    write access validation, and external sharing settings.

    The script is designed for quick review of validation results after running the
    Verify-SiteCreation.ps1 script.

.PARAMETER ReportPath
    Optional path to a specific validation report file. If not provided, the script
    automatically locates the most recent validation report in the reports folder.

.EXAMPLE
    .\Show-ValidationReport.ps1
    
    Displays the most recent validation report with formatted output.

.EXAMPLE
    .\Show-ValidationReport.ps1 -ReportPath "..\reports\site-creation-validation-report-2025-11-16-173535.json"
    
    Displays a specific validation report file.

.NOTES
    Author: Marcus Jacobson
    Version: 1.0.0
    Created: 2025-11-16
    Last Modified: 2025-11-16
    
    Copyright (c) 2025 Marcus Jacobson. All rights reserved.
    Licensed under the MIT License.
    
    Requirements:
    - PowerShell 5.1+ or PowerShell 7+
    - Validation report files generated by Verify-SiteCreation.ps1
    - Read access to reports folder
    
    Script development orchestrated using GitHub Copilot.

.OUTPUTS
    Console output with formatted validation report summary and detailed site results.
#>
#
# =============================================================================
# Script to display the most recent site creation validation report.
# =============================================================================

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [string]$ReportPath
)

# =============================================================================
# Step 1: Locate Most Recent Validation Report
# =============================================================================

Write-Host "🔍 Step 1: Locate Most Recent Validation Report" -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Green

try {
    # Calculate project root directory (go up two levels from scripts folder)
    $projectRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
    $reportsFolder = Join-Path $projectRoot "reports"
    
    if (-not (Test-Path $reportsFolder)) {
        Write-Host "   ❌ Reports folder not found: $reportsFolder" -ForegroundColor Red
        Write-Host "   💡 Run Verify-SiteCreation.ps1 first to generate validation reports" -ForegroundColor Yellow
        exit 1
    }
    
    if ([string]::IsNullOrEmpty($ReportPath)) {
        # Find most recent validation report
        $reportFiles = Get-ChildItem -Path $reportsFolder -Filter "site-creation-validation-report-*.json" -ErrorAction SilentlyContinue
        
        if ($reportFiles.Count -eq 0) {
            Write-Host "   ❌ No validation report files found in: $reportsFolder" -ForegroundColor Red
            Write-Host "   💡 Run Verify-SiteCreation.ps1 first to generate validation reports" -ForegroundColor Yellow
            exit 1
        }
        
        $mostRecentReport = $reportFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        $ReportPath = $mostRecentReport.FullName
    } else {
        if (-not (Test-Path $ReportPath)) {
            Write-Host "   ❌ Specified report file not found: $ReportPath" -ForegroundColor Red
            exit 1
        }
    }
    
    Write-Host "   ✅ Found report: $(Split-Path $ReportPath -Leaf)" -ForegroundColor Green
    Write-Host "   📅 Created: $((Get-Item $ReportPath).LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss'))" -ForegroundColor Cyan
    
} catch {
    Write-Host "   ❌ Error locating validation report - $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# =============================================================================
# Step 2: Load Report Data
# =============================================================================

Write-Host "`n🔍 Step 2: Load Report Data" -ForegroundColor Green
Write-Host "============================" -ForegroundColor Green

try {
    $reportData = Get-Content $ReportPath -Raw | ConvertFrom-Json
    Write-Host "   ✅ Report data loaded successfully" -ForegroundColor Green
    
} catch {
    Write-Host "   ❌ Error loading report data - $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# =============================================================================
# Step 3: Display Validation Summary
# =============================================================================

Write-Host "`n📊 Site Validation Report Summary" -ForegroundColor Cyan
Write-Host "==================================" -ForegroundColor Cyan

# Calculate summary metrics from Results array
$totalSites = $reportData.SitesVerified
$accessibleSites = $reportData.AccessibleSites
$fullyValidatedCount = $reportData.FullyValidatedSites

# Count specific metrics from Results array
$librariesPresent = ($reportData.Results | Where-Object { $_.DocumentLibraryExists -eq $true }).Count
$ownersCorrect = ($reportData.Results | Where-Object { $_.OwnerCorrect -eq $true }).Count
$writeAccessValidated = ($reportData.Results | Where-Object { $_.WriteAccessValidated -eq $true }).Count
$externalSharingDisabled = ($reportData.Results | Where-Object { $_.ExternalSharingDisabled -eq $true }).Count

Write-Host "Sites Verified:              $totalSites" -ForegroundColor White
Write-Host "Accessible Sites:            $accessibleSites" -ForegroundColor White
Write-Host "Document Libraries Present:  $librariesPresent" -ForegroundColor White
Write-Host "Owners Correctly Configured: $ownersCorrect" -ForegroundColor White
Write-Host "Write Access Validated:      $writeAccessValidated" -ForegroundColor White
Write-Host "External Sharing Disabled:   $externalSharingDisabled" -ForegroundColor White
Write-Host "Fully Validated Sites:       $fullyValidatedCount" -ForegroundColor White

# =============================================================================
# Step 4: Display Site-Level Results
# =============================================================================

Write-Host "`n📋 Site-Level Validation Results" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan

# Categorize sites
$fullyValidated = @()
$partiallyValidated = @()
$failed = @()

foreach ($site in $reportData.Results) {
    if ($site.Accessible -and 
        $site.DocumentLibraryExists -and 
        $site.OwnerCorrect -and 
        $site.WriteAccessValidated -and
        $site.MetadataConfigured) {
        $fullyValidated += $site.SiteName
    } elseif ($site.Accessible) {
        $partiallyValidated += $site.SiteName
    } else {
        $failed += $site.SiteName
    }
}

# Display fully validated sites
if ($fullyValidated.Count -gt 0) {
    Write-Host "`n✅ Fully Validated Sites:" -ForegroundColor Green
    foreach ($siteName in $fullyValidated) {
        Write-Host "   • $siteName" -ForegroundColor Green
    }
}

# Display partially validated sites
if ($partiallyValidated.Count -gt 0) {
    Write-Host "`n⚠️  Partially Validated Sites:" -ForegroundColor Yellow
    foreach ($siteName in $partiallyValidated) {
        Write-Host "   • $siteName" -ForegroundColor Yellow
    }
}

# Display failed sites
if ($failed.Count -gt 0) {
    Write-Host "`n❌ Failed Validation:" -ForegroundColor Red
    foreach ($siteName in $failed) {
        Write-Host "   • $siteName" -ForegroundColor Red
    }
}

# =============================================================================
# Step 5: Display External Sharing Status
# =============================================================================

Write-Host "`n🔒 External Sharing Status" -ForegroundColor Cyan
Write-Host "==========================" -ForegroundColor Cyan

$externalSharingDisabledCount = ($reportData.Results | Where-Object { $_.ExternalSharingDisabled -eq $true }).Count
$totalSitesCount = $reportData.Results.Count

if ($externalSharingDisabledCount -eq $totalSitesCount) {
    Write-Host "   ✅ External sharing disabled on all $totalSitesCount sites" -ForegroundColor Green
} else {
    Write-Host "   ⚠️  External sharing status:" -ForegroundColor Yellow
    Write-Host "      Disabled: $externalSharingDisabledCount / $totalSitesCount" -ForegroundColor White
}

# =============================================================================
# Completion
# =============================================================================

Write-Host "`n✅ Report displayed successfully" -ForegroundColor Green
exit 0
