<#
.SYNOPSIS
    Displays the most recent SharePoint site creation report.

.DESCRIPTION
    This script locates and displays the most recent site creation report
    generated by New-SimulatedSharePointSites.ps1. It provides a formatted
    summary of site creation results including created, skipped, and failed sites.

.EXAMPLE
    .\Show-SiteCreationReport.ps1
    
    Displays the most recent site creation report with formatted output.

.NOTES
    Author: Marcus Jacobson
    Version: 1.0.0
    Created: 2025-11-16
    Last Modified: 2025-11-16
    
    Copyright (c) 2025 Marcus Jacobson. All rights reserved.
    Licensed under the MIT License.
    
    Requirements:
    - PowerShell 5.1+ or PowerShell 7+
    - At least one site creation report must exist
    
    Script development orchestrated using GitHub Copilot.

.SHAREPOINT PROVISIONING OPERATIONS
    - Report File Discovery
    - JSON Data Parsing
    - Formatted Console Output
    - Summary Statistics Display
#>
#
# =============================================================================
# Displays formatted summary of SharePoint site creation results.
# =============================================================================

[CmdletBinding()]
param()

# =============================================================================
# Step 1: Locate Most Recent Report
# =============================================================================

Write-Host "🔍 Step 1: Locate Most Recent Site Creation Report" -ForegroundColor Green
Write-Host "===================================================" -ForegroundColor Green

$projectRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$reportsPath = Join-Path $projectRoot "reports"

if (-not (Test-Path $reportsPath)) {
    Write-Host "   ❌ Reports directory not found: $reportsPath" -ForegroundColor Red
    Write-Host "   💡 Tip: Run New-SimulatedSharePointSites.ps1 first to generate a report" -ForegroundColor Yellow
    exit 1
}

$latestReport = Get-ChildItem (Join-Path $reportsPath "site-creation-report-*.json") -ErrorAction SilentlyContinue | 
    Sort-Object LastWriteTime -Descending | 
    Select-Object -First 1

if (-not $latestReport) {
    Write-Host "   ❌ No site creation reports found" -ForegroundColor Red
    Write-Host "   💡 Tip: Run New-SimulatedSharePointSites.ps1 first to generate a report" -ForegroundColor Yellow
    exit 1
}

Write-Host "   ✅ Found report: $($latestReport.Name)" -ForegroundColor Green
Write-Host "   📅 Created: $($latestReport.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss'))" -ForegroundColor Cyan

# =============================================================================
# Step 2: Load and Parse Report Data
# =============================================================================

Write-Host ""
Write-Host "🔍 Step 2: Load Report Data" -ForegroundColor Green
Write-Host "============================" -ForegroundColor Green

try {
    $reportData = Get-Content $latestReport.FullName | ConvertFrom-Json
    Write-Host "   ✅ Report data loaded successfully" -ForegroundColor Green
} catch {
    Write-Host "   ❌ Failed to load report: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# =============================================================================
# Step 3: Display Report Summary
# =============================================================================

Write-Host ""
Write-Host "📊 Site Creation Report Summary" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host "Sites Configured: $($reportData.SitesConfigured)" -ForegroundColor White
Write-Host "Sites Created:    $($reportData.SitesCreated)" -ForegroundColor Green
Write-Host "Sites Skipped:    $($reportData.SitesSkipped)" -ForegroundColor Yellow
Write-Host "Sites Failed:     $($reportData.SitesFailed)" -ForegroundColor Red
Write-Host "Duration:         $($reportData.Duration)" -ForegroundColor White

# =============================================================================
# Step 4: Display Created Sites
# =============================================================================

if ($reportData.CreatedSites.Count -gt 0) {
    Write-Host ""
    Write-Host "✅ Created Sites:" -ForegroundColor Green
    $reportData.CreatedSites | ForEach-Object { 
        Write-Host "   • $_" -ForegroundColor Green 
    }
}

# =============================================================================
# Step 5: Display Skipped Sites
# =============================================================================

if ($reportData.SkippedSites.Count -gt 0) {
    Write-Host ""
    Write-Host "⏭️  Skipped Sites:" -ForegroundColor Yellow
    $reportData.SkippedSites | ForEach-Object { 
        Write-Host "   • $_" -ForegroundColor Yellow 
    }
}

# =============================================================================
# Step 6: Display Failed Sites
# =============================================================================

if ($reportData.FailedSites.Count -gt 0) {
    Write-Host ""
    Write-Host "❌ Failed Sites:" -ForegroundColor Red
    $reportData.FailedSites | ForEach-Object { 
        Write-Host "   • $_" -ForegroundColor Red 
    }
}

# =============================================================================
# Completion
# =============================================================================

Write-Host ""
if ($reportData.SitesFailed -gt 0) {
    Write-Host "⚠️  Some sites failed to create. Review errors and retry if needed." -ForegroundColor Yellow
    exit 1
} else {
    Write-Host "✅ Report displayed successfully" -ForegroundColor Green
    exit 0
}
