trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  - template: pipeline-variables.yml
  - group: 'Purview-Service-Connection'

steps:
  - task: PowerShell@2
    displayName: 'Deploy DLP Policy'
    inputs:
      targetType: 'filePath'
      filePath: '$(System.DefaultWorkingDirectory)/05-Supplemental-IaC-Labs/Data-Loss-Prevention/Deploy-DLP-Policies/Scripts/New-DlpPolicy.ps1'
      arguments: >
        -TenantId $(TenantId)
        -AppId $(AppId)
        -CertificateThumbprint $(CertificateThumbprint)
        -PolicyName "$(PolicyName)"
        -State "$(State)"
      pwsh: true
