<#
.SYNOPSIS
    Analyzes unmapped SIT GUIDs from eDiscovery exports and suggests mappings.

.DESCRIPTION
    This diagnostic script analyzes eDiscovery export results to identify GUIDs
    that couldn't be resolved to friendly SIT names. It provides context about
    where these GUIDs appear and suggests potential mappings based on:
    - File name patterns
    - Co-occurring SITs in the same files
    - Detection frequency and distribution
    - Tenant SIT definitions from Get-DlpSensitiveInformationType

.PARAMETER DetailedAnalysisCsvPath
    Path to the detailed analysis CSV generated by Lab 05b (eDiscovery-Detailed-Analysis-*.csv).
    If provided, analyzes this file instead of the raw eDiscovery export.
    This is the preferred input when called from Lab 05b.

.PARAMETER eDiscoveryExportPath
    Path to the Items_0*.csv file from eDiscovery export.
    If not provided, automatically finds the most recent export in the reports folder.

.PARAMETER OutputJsonPath
    Path where the updated JSON mapping file should be saved.
    Default: ..\Purview-SIT-GUID-Mapping.json

.PARAMETER ShowDetailedAnalysis
    Display detailed analysis including sample files and co-occurrence patterns.

.EXAMPLE
    .\Resolve-UnmappedSITGuids.ps1
    
    Analyzes the most recent eDiscovery export and displays unmapped GUID analysis.

.EXAMPLE
    .\Resolve-UnmappedSITGuids.ps1 -ShowDetailedAnalysis
    
    Performs detailed analysis with file samples and co-occurrence patterns.

.EXAMPLE
    .\Resolve-UnmappedSITGuids.ps1 -eDiscoveryExportPath "..\reports\Items_0_2025-11-18.csv" -OutputJsonPath "..\updated-mapping.json"
    
    Analyzes specific export file and saves suggested mappings to custom location.

.NOTES
    Author: Marcus Jacobson
    Version: 1.0.0
    Created: 2025-11-20
    Last Modified: 2025-11-20
    
    Copyright (c) 2025 Marcus Jacobson. All rights reserved.
    Licensed under the MIT License.
    
    Requirements:
    - PowerShell 5.1+ or PowerShell 7+
    - Security & Compliance PowerShell module (for Get-DlpSensitiveInformationType)
    - Connection to Microsoft 365 tenant (Connect-IPPSSession)
    - eDiscovery export CSV file
    
    Script development orchestrated using GitHub Copilot.

.DIAGNOSTIC APPROACH
    - Extracts all unique GUIDs from eDiscovery export
    - Queries tenant for all available SIT definitions
    - Identifies GUIDs not in tenant (deprecated or custom)
    - Analyzes file context and patterns for clues
    - Suggests potential mappings based on evidence
#>
#
# =============================================================================
# Diagnostic script to resolve unmapped SIT GUIDs from eDiscovery exports.
# =============================================================================

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [string]$DetailedAnalysisCsvPath,
    
    [Parameter(Mandatory = $false)]
    [string]$eDiscoveryExportPath,
    
    [Parameter(Mandatory = $false)]
    [string]$OutputJsonPath = (Join-Path $PSScriptRoot "..\Purview-SIT-GUID-Mapping.json"),
    
    [Parameter(Mandatory = $false)]
    [switch]$ShowDetailedAnalysis
)

# =============================================================================
# Step 1: Load Data for Analysis
# =============================================================================

Write-Host "\n🔍 Step 1: Load Data for Analysis" -ForegroundColor Green
Write-Host "===================================" -ForegroundColor Green

$usingDetailedCsv = $false

# Prioritize detailed analysis CSV if provided (called from Lab 05b)
if ($DetailedAnalysisCsvPath -and (Test-Path $DetailedAnalysisCsvPath)) {
    Write-Host "📊 Loading detailed analysis CSV from Lab 05b..." -ForegroundColor Cyan
    Write-Host "   File: $(Split-Path -Leaf $DetailedAnalysisCsvPath)" -ForegroundColor Gray
    $eDiscoveryData = Import-Csv -Path $DetailedAnalysisCsvPath
    Write-Host "   ✅ Loaded $($eDiscoveryData.Count) detection rows" -ForegroundColor Green
    $usingDetailedCsv = $true
} else {
    # Fall back to raw eDiscovery export
    if (-not $eDiscoveryExportPath) {
        Write-Host "📋 Searching for most recent Items_0 CSV file..." -ForegroundColor Cyan
        $reportsPath = Join-Path $PSScriptRoot "..\05b-eDiscovery-Compliance-Search\reports"
        $items0Csv = Get-ChildItem -Path $reportsPath -Filter "Items_0*.csv" -ErrorAction SilentlyContinue | 
                     Sort-Object LastWriteTime -Descending | 
                     Select-Object -First 1
        
        if ($items0Csv) {
            $eDiscoveryExportPath = $items0Csv.FullName
            Write-Host "   ✅ Found: $(Split-Path $eDiscoveryExportPath -Leaf)" -ForegroundColor Green
        } else {
            Write-Host "   ❌ No Items_0*.csv files found in reports folder" -ForegroundColor Red
            Write-Host "   💡 Please provide -eDiscoveryExportPath parameter" -ForegroundColor Yellow
            exit 1
        }
    }
    
    if (-not (Test-Path $eDiscoveryExportPath)) {
        Write-Host "   ❌ File not found: $eDiscoveryExportPath" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "📄 Loading raw eDiscovery export..." -ForegroundColor Cyan
    $eDiscoveryData = Import-Csv -Path $eDiscoveryExportPath
    Write-Host "   ✅ Loaded $($eDiscoveryData.Count) items" -ForegroundColor Green
}

# =============================================================================
# Step 2: Extract Unique GUIDs from Data
# =============================================================================

Write-Host "`n📊 Step 2: Extract Unique GUIDs from Data" -ForegroundColor Green
Write-Host "===========================================" -ForegroundColor Green

$guidPattern = '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
$allGuids = @{}

if ($usingDetailedCsv) {
    # Extract from SIT_Type column in detailed analysis CSV
    Write-Host "📋 Extracting GUIDs from SIT_Type column..." -ForegroundColor Cyan
    foreach ($row in $eDiscoveryData) {
        if ($row.SIT_Type -match '^Custom SIT \((.+)\)$') {
            $guid = $Matches[1].ToLower()
            if ($allGuids.ContainsKey($guid)) {
                $allGuids[$guid]++
            } else {
                $allGuids[$guid] = 1
            }
        }
    }
} else {
    # Extract from raw Sender/Author column in eDiscovery export
    Write-Host "📋 Extracting GUIDs from raw SIT data..." -ForegroundColor Cyan
    foreach ($item in $eDiscoveryData) {
        $sitData = $item.'Sender/Author'
        if ($sitData) {
            $matches = [regex]::Matches($sitData, $guidPattern)
            foreach ($match in $matches) {
                $guid = $match.Value.ToLower()
                if ($allGuids.ContainsKey($guid)) {
                    $allGuids[$guid]++
                } else {
                    $allGuids[$guid] = 1
                }
            }
        }
    }
}

Write-Host "   ✅ Found $($allGuids.Count) unique GUIDs" -ForegroundColor Green
Write-Host "   📊 Total GUID occurrences: $($allGuids.Values | Measure-Object -Sum | Select-Object -ExpandProperty Sum)" -ForegroundColor Cyan

# =============================================================================
# Step 3: Query Tenant for Available SITs
# =============================================================================

Write-Host "`n🔐 Step 3: Query Tenant SIT Definitions" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Green

try {
    Write-Host "📋 Connecting to Security & Compliance PowerShell..." -ForegroundColor Cyan
    Connect-IPPSSession -ErrorAction SilentlyContinue | Out-Null
    
    Write-Host "🔄 Retrieving all SIT definitions from tenant..." -ForegroundColor Cyan
    $tenantSits = Get-DlpSensitiveInformationType
    
    Write-Host "   ✅ Retrieved $($tenantSits.Count) SIT definitions" -ForegroundColor Green
    
    # Build lookup hashtable
    $tenantSitMap = @{}
    foreach ($sit in $tenantSits) {
        $tenantSitMap[$sit.Id.ToLower()] = $sit.Name
    }
    
} catch {
    Write-Host "   ⚠️ Could not retrieve tenant SIT definitions: $_" -ForegroundColor Yellow
    Write-Host "   💡 Some analysis features will be limited" -ForegroundColor Yellow
    $tenantSitMap = @{}
}

# =============================================================================
# Step 4: Load Existing Centralized Mapping File
# =============================================================================

Write-Host "`n📚 Step 4: Load Existing Centralized Mapping File" -ForegroundColor Green
Write-Host "===================================================" -ForegroundColor Green

$centralizedMappingPath = Join-Path $PSScriptRoot "..\Purview-SIT-GUID-Mapping.json"
$existingMappings = @{}

if (Test-Path $centralizedMappingPath) {
    Write-Host "📄 Loading centralized mapping file..." -ForegroundColor Cyan
    Write-Host "   File: $(Split-Path -Leaf $centralizedMappingPath)" -ForegroundColor Gray
    
    try {
        $mappingContent = Get-Content -Path $centralizedMappingPath -Raw | ConvertFrom-Json
        
        if ($mappingContent.sitMappings) {
            foreach ($property in $mappingContent.sitMappings.PSObject.Properties) {
                $existingMappings[$property.Name.ToLower()] = $property.Value
            }
            Write-Host "   ✅ Loaded $($existingMappings.Count) existing GUID mappings" -ForegroundColor Green
        } else {
            Write-Host "   ⚠️ No sitMappings section found in JSON file" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "   ⚠️ Error loading mapping file: $_" -ForegroundColor Yellow
        Write-Host "   💡 Continuing without existing mappings" -ForegroundColor Yellow
    }
} else {
    Write-Host "   💡 No existing mapping file found at: $centralizedMappingPath" -ForegroundColor Yellow
    Write-Host "   📋 Will create new mapping file with discovered mappings" -ForegroundColor Cyan
}

# =============================================================================
# Step 5: Identify Unmapped GUIDs
# =============================================================================

Write-Host "`n❓ Step 5: Identify Unmapped GUIDs" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green

$unmappedGuids = @()
$mappedGuids = @()

foreach ($guid in $allGuids.Keys) {
    $guidLower = $guid.ToLower()
    
    # Check tenant SIT definitions first
    if ($tenantSitMap.ContainsKey($guidLower)) {
        $mappedGuids += [PSCustomObject]@{
            GUID = $guid
            Name = $tenantSitMap[$guidLower]
            Source = "Tenant"
            Occurrences = $allGuids[$guid]
        }
    # Check centralized mapping file second
    } elseif ($existingMappings.ContainsKey($guidLower)) {
        $mappedGuids += [PSCustomObject]@{
            GUID = $guid
            Name = $existingMappings[$guidLower]
            Source = "Mapping File"
            Occurrences = $allGuids[$guid]
        }
    # GUID not found in either source
    } else {
        $unmappedGuids += [PSCustomObject]@{
            GUID = $guid
            Occurrences = $allGuids[$guid]
        }
    }
}

Write-Host "   ✅ Mapped: $($mappedGuids.Count) GUIDs" -ForegroundColor Green
if ($mappedGuids.Count -gt 0) {
    Write-Host "      📊 Sources:" -ForegroundColor Cyan
    $mappedGuids | Group-Object Source | ForEach-Object {
        Write-Host "         • $($_.Name): $($_.Count) GUIDs" -ForegroundColor Gray
    }
}
Write-Host "   ❌ Unmapped: $($unmappedGuids.Count) GUIDs" -ForegroundColor Red

if ($unmappedGuids.Count -eq 0) {
    Write-Host "`n🎉 Success! All GUIDs are mapped to friendly names!" -ForegroundColor Green
    Write-Host "   💡 No unmapped GUIDs found - all SITs resolved via tenant or mapping file" -ForegroundColor Cyan
    exit 0
}

Write-Host "`n   🔍 Unmapped GUIDs requiring investigation:" -ForegroundColor Yellow
$unmappedGuids | Sort-Object -Property Occurrences -Descending | ForEach-Object {
    Write-Host "      • $($_.GUID) - $($_.Occurrences) occurrences" -ForegroundColor Yellow
}

# =============================================================================
# Step 6: Analyze Context for Unmapped GUIDs
# =============================================================================

Write-Host "`n🔬 Step 6: Analyze Context for Unmapped GUIDs" -ForegroundColor Green
Write-Host "===============================================" -ForegroundColor Green

$contextAnalysis = @()

foreach ($unmappedGuid in $unmappedGuids) {
    Write-Host "`n   📋 Analyzing GUID: $($unmappedGuid.GUID)" -ForegroundColor Cyan
    Write-Host "   $('=' * 80)" -ForegroundColor Cyan
    
    # Find sample files and extract context based on data format
    if ($usingDetailedCsv) {
        # Detailed CSV format: SIT_Type column contains "Custom SIT (guid)"
        $sampleFiles = $eDiscoveryData | Where-Object { 
            $_.SIT_Type -match [regex]::Escape($unmappedGuid.GUID)
        } | Select-Object -First 10
        
        # Extract file name patterns from FileName column
        $fileNames = $sampleFiles | Select-Object -ExpandProperty FileName -Unique | Where-Object { $_ }
        $fileNamePattern = ($fileNames | ForEach-Object { 
            if ($_ -match '^([A-Za-z]+)_') { $matches[1] } 
        } | Group-Object | Sort-Object Count -Descending | Select-Object -First 1).Name
        
        # Get co-occurring SITs from same files
        $filesWithUnmappedGuid = $sampleFiles | Select-Object -ExpandProperty FileName -Unique
        $coOccurringSitNames = @{}
        
        foreach ($fileName in $filesWithUnmappedGuid) {
            # Get all SIT detections for this file
            $allSitsInFile = $eDiscoveryData | Where-Object { $_.FileName -eq $fileName }
            
            foreach ($detection in $allSitsInFile) {
                $sitType = $detection.SIT_Type
                # Only count if it's not our unmapped GUID and not another Custom SIT
                if ($sitType -and $sitType -notmatch [regex]::Escape($unmappedGuid.GUID) -and $sitType -notmatch '^Custom SIT \(') {
                    if ($coOccurringSitNames.ContainsKey($sitType)) {
                        $coOccurringSitNames[$sitType]++
                    } else {
                        $coOccurringSitNames[$sitType] = 1
                    }
                }
            }
        }
        
        # Build co-occurring SITs list with friendly names
        $coOccurringSits = $coOccurringSitNames.Keys | ForEach-Object {
            [PSCustomObject]@{
                Name = $_
                CoOccurrences = $coOccurringSitNames[$_]
            }
        } | Sort-Object -Property CoOccurrences -Descending | Select-Object -First 5
        
    } else {
        # Raw eDiscovery export format: Sender/Author column contains raw GUID data
        $sampleFiles = $eDiscoveryData | Where-Object { 
            $_.'Sender/Author' -match $unmappedGuid.GUID 
        } | Select-Object -First 10
        
        # Extract file name patterns
        $fileNames = $sampleFiles | Select-Object -ExpandProperty 'File name' | Where-Object { $_ }
        $fileNamePattern = ($fileNames | ForEach-Object { 
            if ($_ -match '^([A-Za-z]+)_') { $matches[1] } 
        } | Group-Object | Sort-Object Count -Descending | Select-Object -First 1).Name
        
        # Extract co-occurring GUIDs (other SITs detected in same files)
        $coOccurringGuids = @{}
        foreach ($file in $sampleFiles) {
            $sitData = $file.'Sender/Author'
            if ($sitData) {
                $matches = [regex]::Matches($sitData, $guidPattern)
                foreach ($match in $matches) {
                    $guid = $match.Value.ToLower()
                    if ($guid -ne $unmappedGuid.GUID) {
                        if ($coOccurringGuids.ContainsKey($guid)) {
                            $coOccurringGuids[$guid]++
                        } else {
                            $coOccurringGuids[$guid] = 1
                        }
                    }
                }
            }
        }
        
        # Map co-occurring GUIDs to names
        $coOccurringSits = $coOccurringGuids.Keys | ForEach-Object {
            $coGuid = $_
            $sitName = if ($tenantSitMap.ContainsKey($coGuid)) { 
                $tenantSitMap[$coGuid] 
            } else { 
                "Custom SIT ($coGuid)" 
            }
            [PSCustomObject]@{
                GUID = $coGuid
                Name = $sitName
                CoOccurrences = $coOccurringGuids[$coGuid]
            }
        } | Sort-Object -Property CoOccurrences -Descending | Select-Object -First 5
    }
    
    Write-Host "      📊 Occurrences: $($unmappedGuid.Occurrences)" -ForegroundColor White
    Write-Host "      📁 File Pattern: $(if ($fileNamePattern) { $fileNamePattern } else { 'None detected' })" -ForegroundColor White
    Write-Host "      🔗 Co-occurring SITs:" -ForegroundColor White
    
    if ($coOccurringSits) {
        foreach ($coSit in $coOccurringSits) {
            Write-Host "         • $($coSit.Name) ($($coSit.CoOccurrences) times)" -ForegroundColor Gray
        }
    } else {
        Write-Host "         (No co-occurring SITs found)" -ForegroundColor Gray
    }
    
    if ($ShowDetailedAnalysis) {
        Write-Host "`n      📄 Sample Files:" -ForegroundColor White
        if ($usingDetailedCsv) {
            $sampleFiles | Select-Object -First 3 | ForEach-Object {
                Write-Host "         • $($_.FileName)" -ForegroundColor Gray
            }
        } else {
            $sampleFiles | Select-Object -First 3 | ForEach-Object {
                Write-Host "         • $($_.'File name')" -ForegroundColor Gray
            }
        }
    }
    
    # Store context analysis for Step 8
    $contextAnalysis += [PSCustomObject]@{
        GUID = $unmappedGuid.GUID
        Occurrences = $unmappedGuid.Occurrences
        FilePattern = if ($fileNamePattern) { $fileNamePattern } else { $null }
        TopCoOccurringSIT = if ($coOccurringSits) { $coOccurringSits[0].Name } else { $null }
        AllCoOccurringSITs = $coOccurringSits
        SuggestedAction = "Manual investigation required"
    }
}

# =============================================================================
# Step 7: Generate Recommendations
# =============================================================================

Write-Host "\n💡 Step 7: Recommendations" -ForegroundColor Green
Write-Host "===========================" -ForegroundColor Green

Write-Host "`n   📋 Summary of Unmapped GUIDs:" -ForegroundColor Cyan
$contextAnalysis | Format-Table -Property GUID, Occurrences, FilePattern, TopCoOccurringSIT -AutoSize

Write-Host "`n   🔍 Investigation Steps:" -ForegroundColor Yellow
Write-Host "      1. Check Purview portal for these GUIDs in 'Sensitive info types'" -ForegroundColor White
Write-Host "      2. Look for pattern matching logic (Function processors, Keywords)" -ForegroundColor White
Write-Host "      3. Compare file name patterns with SIT definitions" -ForegroundColor White
Write-Host "      4. Review co-occurring SITs for context clues" -ForegroundColor White
Write-Host "      5. Test sample files with known SIT patterns" -ForegroundColor White

Write-Host "`n   📝 To Update JSON Mapping:" -ForegroundColor Yellow
Write-Host "      1. Open: $OutputJsonPath" -ForegroundColor White
Write-Host "      2. Add entries in the 'sitMappings' section:" -ForegroundColor White
Write-Host "         `"guid-here`": `"Friendly SIT Name`"" -ForegroundColor Gray
Write-Host "      3. Save the file" -ForegroundColor White
Write-Host "      4. Re-run Lab 05b analysis to verify mappings" -ForegroundColor White

Write-Host "`n   🔗 Helpful Resources:" -ForegroundColor Yellow
Write-Host "      • Purview Portal: https://compliance.microsoft.com/classifiers?viewid=sensitiveTypes" -ForegroundColor White
Write-Host "      • Microsoft Learn SIT Definitions: https://learn.microsoft.com/en-us/purview/sit-sensitive-information-type-entity-definitions" -ForegroundColor White

# =============================================================================
# Step 8: Optional - Generate JSON Update Template
# =============================================================================

Write-Host "\n📄 Step 8: Generate JSON Update Template" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green

$jsonTemplate = @"
{
  "suggestedMappings": {
    "note": "Add these entries to your Purview-SIT-GUID-Mapping.json file after verifying the correct SIT names",
    "entries": {
"@

foreach ($unmapped in $unmappedGuids) {
    $jsonTemplate += "`n      `"$($unmapped.GUID)`": `"TODO: Add friendly SIT name here`","
}

$jsonTemplate = $jsonTemplate.TrimEnd(',')
$jsonTemplate += @"

    }
  }
}
"@

$templatePath = Join-Path $PSScriptRoot "unmapped-guids-template.json"
$jsonTemplate | Out-File -FilePath $templatePath -Encoding UTF8
Write-Host "   ✅ Template saved: $templatePath" -ForegroundColor Green

# =============================================================================
# Step 9: Interactive Mapping Confirmation with Context-Based Suggestions
# =============================================================================

Write-Host "`n🔄 Step 9: Interactive SIT Mapping Update" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green

$newMappings = @{}

foreach ($unmapped in $unmappedGuids | Sort-Object -Property Occurrences -Descending) {
    Write-Host "`n📋 Unmapped GUID: $($unmapped.GUID)" -ForegroundColor Cyan
    Write-Host "   📊 Occurrences: $($unmapped.Occurrences)" -ForegroundColor White
    
    # Try to find in tenant (one more time with fresh query)
    if ($tenantSitMap.Count -gt 0) {
        $tenantMatch = $tenantSitMap[$unmapped.GUID]
        if ($tenantMatch) {
            Write-Host "   ✅ Found in tenant: $tenantMatch" -ForegroundColor Green
            Write-Host "`n   Would you like to add this mapping to the JSON file? (Y/N)" -ForegroundColor Yellow
            $response = Read-Host "   Response"
            
            if ($response -eq 'Y' -or $response -eq 'y') {
                $newMappings[$unmapped.GUID] = $tenantMatch
                Write-Host "   ✅ Mapping queued for addition" -ForegroundColor Green
            } else {
                Write-Host "   ⏭️  Skipped" -ForegroundColor Gray
            }
            continue
        }
    }
    
    # Not in tenant - analyze context and provide suggestions
    Write-Host "   ❌ Not found in tenant SIT definitions" -ForegroundColor Red
    
    # Find the context analysis for this GUID
    $context = $contextAnalysis | Where-Object { $_.GUID -eq $unmapped.GUID }
    
    # Build intelligent suggestion based on context
    $suggestion = $null
    $suggestionReason = ""
    
    if ($context) {
        # Check for strong file pattern matches
        if ($context.FilePattern -and $context.FilePattern -ne 'Unknown') {
            $patternLower = $context.FilePattern.ToLower()
            
            # Pattern-based suggestions
            $patternSuggestions = @{
                'payroll' = 'Payroll Data'
                'salary' = 'Salary Information'
                'benefits' = 'Employee Benefits Data'
                'tax' = 'Tax Document'
                'ssn' = 'Social Security Number'
                'passport' = 'Passport Number'
                'drivers' = 'Driver License Number'
                'license' = 'License Number'
                'medical' = 'Medical Record Number'
                'patient' = 'Patient Identifier'
                'credit' = 'Credit Card Number'
                'bank' = 'Bank Account Number'
                'routing' = 'Bank Routing Number'
                'iban' = 'International Bank Account Number'
                'contract' = 'Contract Identifier'
                'confidential' = 'Confidential Document'
            }
            
            foreach ($pattern in $patternSuggestions.Keys) {
                if ($patternLower -match $pattern) {
                    $suggestion = $patternSuggestions[$pattern]
                    $suggestionReason = "file pattern: $($context.FilePattern)"
                    break
                }
            }
        }
        
        # Check co-occurring SITs for context clues
        if (-not $suggestion -and $context.TopCoOccurringSIT -and $context.TopCoOccurringSIT -ne 'None') {
            $coSitLower = $context.TopCoOccurringSIT.ToLower()
            
            # Co-occurrence-based suggestions
            if ($coSitLower -match 'social security') {
                $suggestion = "Related SSN Pattern"
                $suggestionReason = "co-occurs with: $($context.TopCoOccurringSIT)"
            } elseif ($coSitLower -match 'passport') {
                $suggestion = "Related Passport Pattern"
                $suggestionReason = "co-occurs with: $($context.TopCoOccurringSIT)"
            } elseif ($coSitLower -match 'tax') {
                $suggestion = "Related Tax Identifier"
                $suggestionReason = "co-occurs with: $($context.TopCoOccurringSIT)"
            } elseif ($coSitLower -match 'bank|routing|aba') {
                $suggestion = "Related Banking Information"
                $suggestionReason = "co-occurs with: $($context.TopCoOccurringSIT)"
            } elseif ($coSitLower -match 'credit|card') {
                $suggestion = "Related Payment Information"
                $suggestionReason = "co-occurs with: $($context.TopCoOccurringSIT)"
            }
        }
        
        # Check occurrence patterns (high volume suggests common built-in SIT)
        if (-not $suggestion -and $unmapped.Occurrences -gt 1000) {
            $suggestion = "Deprecated Built-in SIT (High Volume)"
            $suggestionReason = "high occurrence count suggests former Microsoft SIT"
        }
    }
    
    # Present options based on whether we have a suggestion
    Write-Host "`n   Options:" -ForegroundColor Yellow
    
    if ($suggestion) {
        Write-Host "   💡 Suggested mapping based on $suggestionReason" -ForegroundColor Cyan
        Write-Host "   1. Use suggested name: `"$suggestion`"" -ForegroundColor White
        Write-Host "   2. Enter custom friendly SIT name (if this is a tenant-specific custom SIT)" -ForegroundColor White
        Write-Host "   3. Skip for now (will remain as 'Custom SIT (guid)')" -ForegroundColor White
        $choice = Read-Host "`n   Enter choice (1/2/3)"
        
        if ($choice -eq '1') {
            Write-Host "`n   Using suggested name: '$suggestion'" -ForegroundColor White
            Write-Host "   Confirm this mapping? (Y/N)" -ForegroundColor Yellow
            $confirm = Read-Host "   Response"
            
            if ($confirm -eq 'Y' -or $confirm -eq 'y') {
                $newMappings[$unmapped.GUID] = $suggestion
                Write-Host "   ✅ Mapping queued for addition" -ForegroundColor Green
            } else {
                Write-Host "   ⏭️  Cancelled" -ForegroundColor Gray
            }
        } elseif ($choice -eq '2') {
            Write-Host "`n   Enter the friendly SIT name:" -ForegroundColor Cyan
            $friendlyName = Read-Host "   SIT Name"
            
            if ($friendlyName -and $friendlyName.Trim() -ne '') {
                Write-Host "`n   You entered: '$friendlyName'" -ForegroundColor White
                Write-Host "   Confirm this mapping? (Y/N)" -ForegroundColor Yellow
                $confirm = Read-Host "   Response"
                
                if ($confirm -eq 'Y' -or $confirm -eq 'y') {
                    $newMappings[$unmapped.GUID] = $friendlyName.Trim()
                    Write-Host "   ✅ Mapping queued for addition" -ForegroundColor Green
                } else {
                    Write-Host "   ⏭️  Cancelled" -ForegroundColor Gray
                }
            } else {
                Write-Host "   ⏭️  Skipped (no name provided)" -ForegroundColor Gray
            }
        } else {
            Write-Host "   ⏭️  Skipped" -ForegroundColor Gray
        }
    } else {
        # No suggestion available - simplified options
        Write-Host "   💭 No automatic suggestion available based on context" -ForegroundColor Gray
        Write-Host "   1. Enter custom friendly SIT name (if you've identified it)" -ForegroundColor White
        Write-Host "   2. Skip for now (will remain as 'Custom SIT (guid)')" -ForegroundColor White
        $choice = Read-Host "`n   Enter choice (1/2)"
        
        if ($choice -eq '1') {
            Write-Host "`n   Enter the friendly SIT name:" -ForegroundColor Cyan
            $friendlyName = Read-Host "   SIT Name"
            
            if ($friendlyName -and $friendlyName.Trim() -ne '') {
                Write-Host "`n   You entered: '$friendlyName'" -ForegroundColor White
                Write-Host "   Confirm this mapping? (Y/N)" -ForegroundColor Yellow
                $confirm = Read-Host "   Response"
                
                if ($confirm -eq 'Y' -or $confirm -eq 'y') {
                    $newMappings[$unmapped.GUID] = $friendlyName.Trim()
                    Write-Host "   ✅ Mapping queued for addition" -ForegroundColor Green
                } else {
                    Write-Host "   ⏭️  Cancelled" -ForegroundColor Gray
                }
            } else {
                Write-Host "   ⏭️  Skipped (no name provided)" -ForegroundColor Gray
            }
        } else {
            Write-Host "   ⏭️  Skipped" -ForegroundColor Gray
        }
    }
}

# =============================================================================
# Step 9: Update JSON Mapping File
# =============================================================================

if ($newMappings.Count -gt 0) {
    Write-Host "`n💾 Step 9: Update JSON Mapping File" -ForegroundColor Green
    Write-Host "====================================" -ForegroundColor Green
    
    Write-Host "   📋 New mappings to add: $($newMappings.Count)" -ForegroundColor Cyan
    $newMappings.GetEnumerator() | ForEach-Object {
        Write-Host "      • $($_.Key) → $($_.Value)" -ForegroundColor White
    }
    
    try {
        # Load existing JSON
        if (Test-Path $OutputJsonPath) {
            $jsonContent = Get-Content -Path $OutputJsonPath -Raw | ConvertFrom-Json
        } else {
            # Create new JSON structure
            $jsonContent = [PSCustomObject]@{
                metadata = [PSCustomObject]@{
                    description = "Universal GUID-to-Friendly-Name mapping for Microsoft Purview built-in Sensitive Information Types (SITs)"
                    purpose = "Maps eDiscovery export GUIDs to human-readable SIT names for reporting and analysis"
                    lastUpdated = (Get-Date -Format "yyyy-MM-dd")
                }
                sitMappings = [PSCustomObject]@{}
            }
        }
        
        # Add new mappings
        foreach ($mapping in $newMappings.GetEnumerator()) {
            $jsonContent.sitMappings | Add-Member -MemberType NoteProperty -Name $mapping.Key -Value $mapping.Value -Force
        }
        
        # Update metadata
        $jsonContent.metadata.lastUpdated = Get-Date -Format "yyyy-MM-dd"
        
        # Save updated JSON
        $jsonContent | ConvertTo-Json -Depth 10 | Out-File -FilePath $OutputJsonPath -Encoding UTF8
        
        Write-Host "`n   ✅ Successfully updated: $OutputJsonPath" -ForegroundColor Green
        Write-Host "   📊 Total mappings in file: $($jsonContent.sitMappings.PSObject.Properties.Count)" -ForegroundColor Cyan
        
        Write-Host "`n   🔄 Next Steps:" -ForegroundColor Yellow
        Write-Host "      1. Re-run Lab 05b analysis to apply new mappings" -ForegroundColor White
        Write-Host "      2. Verify 'Custom SIT (guid)' entries are now resolved" -ForegroundColor White
        Write-Host "      3. Check that confidence levels show 'High' for resolved SITs" -ForegroundColor White
        
    } catch {
        Write-Host "`n   ❌ Error updating JSON file: $_" -ForegroundColor Red
        Write-Host "   💡 Manual update required - see template file: $templatePath" -ForegroundColor Yellow
    }
} else {
    Write-Host "`n⏭️  No new mappings added" -ForegroundColor Gray
}

Write-Host "`n✅ Analysis complete!" -ForegroundColor Green
Write-Host "📊 Analyzed $($unmappedGuids.Count) unmapped GUIDs" -ForegroundColor Cyan
